=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/layout-mapping-schema.json
{
   "id": "http://www.ibm.com/schemas/layout-mapping-schema.json",
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Layout Mapping Schema",
   "description": "Schema for Layout Mappings",
   "type": "object",
   "properties": {
      "id": {
         "type": "string",
         "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
         "maxLength": 100
      },
      "rev": { "type": "string" },
      "_revisions": { "type": "object" },
      "name": {
         "type": "string",
         "minLength": 1,
         "maxLength": 250
      },
      "classification": { "enum": [ "layout-mapping" ] },
      "path" : { "type":  "string" },
      "type": {
         "type":  "object",
         "properties" : {
            "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
            "name" : { "type":  "string", "maxLength": 250 }
         },
         "additionalProperties": false
      },
      "creatorId": { "type": "string" },
      "created": { "type": "string", "format": "date-time" },
      "lastModifierId": { "type": "string" },
      "lastModified": { "type": "string", "format": "date-time" },
      "tags": {
         "type": "array",
         "items": {
            "type": "string"
         },
         "maxItems": 100,
         "uniqueItems": true
      },
      "mappings": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "layoutMode": { "type":  "string", "minLength": 1, "maxLength": 100 },
               "defaultLayout": {
                  "type":  "object",
                  "properties" : {
                     "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
                     "name" : { "type":  "string", "maxLength": 250 }
                  },
                  "required": [ "id" ],
                  "additionalProperties": false
               },
               "layouts": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "id": { "type": "string", "minLength": 1, "maxLength": 100 },
                        "name": { "type": "string", "maxLength": 250 }
                     },
                     "required": [ "id" ],
                     "additionalProperties": false
                  },
                  "minItems": 1,
                  "maxItems": 50,
                  "uniqueItems": true
               }
            },
            "required": [ "defaultLayout", "layouts" ],
            "additionalProperties": false
         },
         "minItems": 1,
         "maxItems": 50,
         "uniqueItems": true
      }
   },
   "additionalProperties": false,
   "required": [
      "name",
      "type",
      "classification",
      "mappings"
   ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/sites-rows-layout-mapping.json
{
  "id": "sites-rows-layout-mapping",
  "rev": "1-cc5f14a90e23b65e68b5d9737fc5a29a",
  "name": "sitesRowsLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "9ca02297-a564-40c9-aedc-add9c30f3d7b"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "sites-rows-layout"
      },
      "layouts": [
        {
          "id": "sites-rows-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layout-mappings/image-component-layout-mapping.json
{
  "id": "image-component-layout-mapping",
  "rev": "4-ca15803d0f39b41944c5187d570a0c03",
  "name": "imageComponentLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "b7b05524-87ed-4509-b6fb-972f2cbf26d5"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "image-component-layout"
      },
      "layouts": [
        {
          "id": "image-component-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/link-bar-component-layout-mapping.json
{
  "id": "link-bar-component-layout-mapping",
  "rev": "1-8e8c8223c75e2a3040a4f508c7bceb05",
  "name": "linkBarComponentLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "98bec4ac-6170-402c-9405-6e8cfd99508a"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "link-bar-component-layout"
      },
      "layouts": [
        {
          "id": "link-bar-component-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/layout-mappings/sites-html-layout-mapping.json
{
  "name": "sitesHtmlLayoutMapping",
  "id": "sites-html-layout-mapping",
  "classification": "layout-mapping",
  "mappings": [
    {
      "defaultLayout": {
        "name": "sitesHtmlLayout",
        "id": "sites-html-layout"
      },
      "layouts": [
        {
          "name": "sitesHtmlLayout",
          "id": "sites-html-layout"
        }
      ]
    }
  ],
  "tags": [
    "sites-next"
  ],
  "type": {
    "name": "Sites HTML",
    "id": "85bdc88c-5b4c-4002-a665-37ba5bf95cb6"
  },
  "rev": "0-8ef50852-11d4-4b7c-88b0-18f0f83b00db"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/stuart/layout-mappings/Copy of Hero image.json
{
  "id": "37e55061-804c-4120-9c3c-240dfca6ca79",
  "rev": "1-e7e838941ea9e275de63a745b5415bf4",
  "name": "Copy of Hero image",
  "classification": "layout-mapping",
  "type": {
    "id": "8e555ce3-d7fb-462b-8cdc-4e638e9ab4d4"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "hero-image-layout"
      },
      "layouts": [
        {
          "id": "hero-image-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/image-text-component-layout-mapping.json
{
  "id": "image-text-component-layout-mapping",
  "rev": "1-1b411efd452789e24c7688fac8efd6f0",
  "name": "imageTextComponentLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "4e70d4a0-0112-43c5-887b-dde336ebe678"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "image-text-component-layout"
      },
      "layouts": [
        {
          "id": "image-text-component-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-types/data/layout-mappings/page-descriptor-layout-mapping.json
{
  "name": "pageDescriptorLayoutMapping",
  "id": "page-descriptor-layout-mapping",
  "classification": "layout-mapping",
  "mappings": [
    {
      "defaultLayout": {
        "name": "pageDescriptorLayout",
        "id": "page-descriptor-layout"
      },
      "layouts": [
        {
          "name": "pageDescriptorLayout",
          "id": "page-descriptor-layout"
        }
      ]
    }
  ],
  "tags": [
    "sites-next"
  ],
  "type": {
    "name": "Page Descriptor",
    "id": "74f83bd2-2ef6-43f9-8264-bd538e5aad28"
  },
  "rev": "0-893938f2-c87c-4356-bd86-d9bb2d645576"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layout-mappings/all-types-page-layout-mapping.json
{
  "id": "b76c47e5-b0c0-419e-bd18-bb8b3b02ff50",
  "rev": "2-4025994704cf89b08492d162a4536161",
  "name": "All types page",
  "classification": "layout-mapping",
  "type": {
    "id": "9f8e8bb3-ae85-4827-9850-2397141a0f21",
    "name": "All types page"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "all-types-page-layout",
        "name": "One column"
      },
      "layouts": [
        {
          "id": "all-types-page-layout",
          "name": "One column"
        },
        {
          "id": "all-types-page-hero-2-blocks",
          "name": "Three blocks"
        },
        {
          "id": "all-types-page-hero-4-blocks",
          "name": "Five blocks"
        }
      ]
    }
  ]
}
