=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/layout-mapping-schema.json
{
   "id": "http://www.ibm.com/schemas/layout-mapping-schema.json",
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Layout Mapping Schema",
   "description": "Schema for Layout Mappings",
   "type": "object",
   "properties": {
      "id": {
         "type": "string",
         "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
         "maxLength": 100
      },
      "rev": { "type": "string" },
      "_revisions": { "type": "object" },
      "name": {
         "type": "string",
         "minLength": 1,
         "maxLength": 250
      },
      "classification": { "enum": [ "layout-mapping" ] },
      "path" : { "type":  "string" },
      "type": {
         "type":  "object",
         "properties" : {
            "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
            "name" : { "type":  "string", "maxLength": 250 }
         },
         "additionalProperties": false
      },
      "creatorId": { "type": "string" },
      "created": { "type": "string", "format": "date-time" },
      "lastModifierId": { "type": "string" },
      "lastModified": { "type": "string", "format": "date-time" },
      "tags": {
         "type": "array",
         "items": {
            "type": "string"
         },
         "maxItems": 100,
         "uniqueItems": true
      },
      "mappings": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "layoutMode": { "type":  "string", "minLength": 1, "maxLength": 100 },
               "defaultLayout": {
                  "type":  "object",
                  "properties" : {
                     "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
                     "name" : { "type":  "string", "maxLength": 250 }
                  },
                  "required": [ "id" ],
                  "additionalProperties": false
               },
               "layouts": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "id": { "type": "string", "minLength": 1, "maxLength": 100 },
                        "name": { "type": "string", "maxLength": 250 }
                     },
                     "required": [ "id" ],
                     "additionalProperties": false
                  },
                  "minItems": 1,
                  "maxItems": 50,
                  "uniqueItems": true
               }
            },
            "required": [ "defaultLayout", "layouts" ],
            "additionalProperties": false
         },
         "minItems": 1,
         "maxItems": 50,
         "uniqueItems": true
      }
   },
   "additionalProperties": false,
   "required": [
      "name",
      "type",
      "classification",
      "mappings"
   ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layout-mappings/design-article-layout-mapping.json
{
  "id": "design-article-layout-mapping",
  "rev": "2-7fc12da169997694a5f3a285db5ba003",
  "name": "designArticleLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "a8fa51a3-4919-4308-a0b3-6cd31ae15d7e",
    "name": "Design article"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "design-article-layout",
        "name": "Design article"
      },
      "layouts": [
        {
          "id": "design-article-layout",
          "name": "Design article"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/page-contribution-layout-mapping.json
{
  "id": "page-contribution-layout-mapping",
  "rev": "3-3b186e04b84b5e1a0d0ed0179787408d",
  "name": "pageContributionLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "354743b2-f89a-482b-b447-2b5a2367c8bd"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "page-contribution-layout"
      },
      "layouts": [
        {
          "id": "page-contribution-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/layout-mappings/page-script-contribution-layout-mapping.json
{
  "name": "pageScriptContributionLayoutMapping",
  "id": "page-script-contribution-layout-mapping",
  "classification": "layout-mapping",
  "mappings": [
    {
      "defaultLayout": {
        "name": "pageScriptContributionLayout",
        "id": "page-script-contribution-layout"
      },
      "layouts": [
        {
          "name": "pageScriptContributionLayout",
          "id": "page-script-contribution-layout"
        }
      ]
    }
  ],
  "tags": [
    "sites-next"
  ],
  "type": {
    "name": "Page Script Contribution",
    "id": "5c473463-db07-4132-b8a1-bd40cbdf4b18"
  },
  "rev": "0-cb8756dc-0998-420a-8586-62b0945d580d"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/layout-mappings/sites-social-follow-layout-mapping.json
{
  "name": "sitesSocialFollowLayoutMapping",
  "id": "sites-social-follow-layout-mapping",
  "classification": "layout-mapping",
  "mappings": [
    {
      "defaultLayout": {
        "name": "sitesSocialFollowLayout",
        "id": "sites-social-follow-layout"
      },
      "layouts": [
        {
          "name": "sitesSocialFollowLayout",
          "id": "sites-social-follow-layout"
        }
      ]
    }
  ],
  "tags": [
    "sites-next"
  ],
  "type": {
    "name": "Sites Social Follow",
    "id": "669768ce-44c7-4de3-83c1-a72d871e8df2"
  },
  "rev": "0-9c34013d-a3ff-4bdf-a6bc-39ff46670304"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/design-article-layout-mapping.json
{
  "id": "design-article-layout-mapping",
  "rev": "1-9ff2f9680194978a05018df0c0768c88",
  "name": "designArticleLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "a8fa51a3-4919-4308-a0b3-6cd31ae15d7e"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "design-article-layout"
      },
      "layouts": [
        {
          "id": "design-article-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/text-component-layout-mapping.json
{
  "id": "text-component-layout-mapping",
  "rev": "1-884c6b69ab15a638e94b0eada4f008e4",
  "name": "textComponentLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "09ed64f3-23d9-48bb-871d-e00430751ea6"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "text-component-layout"
      },
      "layouts": [
        {
          "id": "text-component-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/sites-image-layout-mapping.json
{
  "id": "sites-image-layout-mapping",
  "rev": "1-1bf14278518d3669c5af32668a95ec37",
  "name": "sitesImageLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "c8295d37-7235-495e-8d40-f3b8bafe4099"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "sites-image-layout"
      },
      "layouts": [
        {
          "id": "sites-image-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/sites-html-layout-mapping.json
{
  "id": "sites-html-layout-mapping",
  "rev": "1-e0ff3f9100a1c08db9ac14a5b85ac8da",
  "name": "sitesHtmlLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "85bdc88c-5b4c-4002-a665-37ba5bf95cb6"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "sites-html-layout"
      },
      "layouts": [
        {
          "id": "sites-html-layout"
        }
      ]
    }
  ]
}
