=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/layout-schema.json
{
  "id": "http://www.ibm.com/schemas/layout-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Layout Schema",
  "description": "Schema for Layout",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
      "maxLength": 100
    },
    "rev": {"type": "string" },
    "_revisions": { "type": "object" },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 250
    },
    "path" : { "type":  "string" },
    "description": {"type": "string", "maxLength": 500 },
    "classification": {"enum": [ "layout" ] },
    "creatorId": {"type": "string"},
    "created": {"type": "string", "format": "date-time" },
    "lastModifierId": {"type": "string"},
    "lastModified": {"type": "string", "format": "date-time" },
    "thumbnail": {
      "type":  "object",
      "properties" : {
        "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
        "path" : { "type":  "string" },
        "url" : { "type":  "string" }
      },
      "additionalProperties": false
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 100,
      "uniqueItems": true
    },
    "template": { "type": "string", "minLength" : 1 },
    "templateType": {
      "enum": [
        "handlebars",
        "angular"
      ]
    },
    "prerender": {
      "type": "boolean"
    },
    "urlTemplate": { "type": "string" }
  },
  "required": ["name", "classification", "template"],
  "additionalProperties": false
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layouts/d8f3731d-4b51-4fef-a9b0-662ae824d8af.json
{
  "id": "d8f3731d-4b51-4fef-a9b0-662ae824d8af",
  "rev": "2-3c426dd2eaceb8bfbc4653c9592bd17a",
  "name": "Email Layout",
  "classification": "layout",
  "prerender": true,
  "template": "/email/Email-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/Email-layout/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/stuart/layouts/all-types-page-hero-2-blocks.json
{
  "id": "all-types-page-hero-2-blocks",
  "rev": "1-d4df691f79b900e2e0a6ffea893dbadc",
  "name": "Three blocks",
  "classification": "layout",
  "prerender": false,
  "thumbnail": {
    "path": "/layouts/thumbnails/standard-page-hero-2-blocks_220.svg"
  },
  "template": "all-types-page-hero-2-blocks",
  "templateType": "angular"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layouts/contest-rules-layout.json
{
  "id": "contest-rules-layout",
  "rev": "2-2e0c02ec85939a83b31d50e7ac5c09b6",
  "name": "One Column",
  "classification": "layout",
  "prerender": false,
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/contest-rules-layout.jpg"
  },
  "template": "contest-rules-layout",
  "templateType": "angular"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/layouts/sites-navigation-page-layout.json
{
  "name": "siteNavigationPageLayout",
  "id": "sites-navigation-page-layout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next"
  ],
  "template": "/dxdam/templates/sites-navigation-page-layout.hbs",
  "templateType": "handlebars",
  "thumbnail": {
    "path": "/dxauth/thumbnails/layouts/sites-navigation-page-layout.jpg"
  },
  "urlTemplate": "{templateLocation}/sites-navigation-page-layout/{id}.html",
  "rev": "0-8cf720e5-6f8f-4028-95cd-d53ba20a973d"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/divider-component-layout.json
{
  "id": "divider-component-layout",
  "rev": "1-8bd26ec8fef771541a8d2799037799cb",
  "name": "dividerComponentLayout",
  "classification": "layout",
  "prerender": true,
  "template": "/email/components/divider-component-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "/emails/{name}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-types/data/layouts/page-embed-contribution-layout.json
{
  "name": "pageEmbedContributionLayout",
  "id": "page-embed-contribution-layout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "template": "/dxdam/templates/page-embed-contribution-layout.hbs",
  "templateType": "handlebars",
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/page-contributions-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_63b3f57e91735eaa985f3ace1e44f38a"
  },
  "urlTemplate": "{templateLocation}/sites/page-embed-contribution/{id}.html",
  "rev": "0-5c696d2e-412a-4783-be51-6d74bec90331"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-layouts/data/layouts/page-script-contribution-layout.json
{
  "id": "page-script-contribution-layout",
  "rev": "3-69b966b3c37af1cfb43bb05d0eca3b52",
  "name": "pageScriptContributionLayout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/page-contributions-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_63b3f57e91735eaa985f3ace1e44f38a"
  },
  "template": "/sites/templates/page-script-contribution-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/sites/page-script-contribution/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/all-types-page-layout.json
{
  "id": "all-types-page-layout",
  "rev": "1-338ae5648bf32aa4d8ebddddf2373138",
  "name": "One column",
  "classification": "layout",
  "prerender": false,
  "thumbnail": {
    "path": "/layouts/thumbnails/standard-page-hero_220.svg"
  },
  "template": "all-types-page-layout",
  "templateType": "angular"
}
