=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/layout-mapping-schema.json
{
   "id": "http://www.ibm.com/schemas/layout-mapping-schema.json",
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Layout Mapping Schema",
   "description": "Schema for Layout Mappings",
   "type": "object",
   "properties": {
      "id": {
         "type": "string",
         "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
         "maxLength": 100
      },
      "rev": { "type": "string" },
      "_revisions": { "type": "object" },
      "name": {
         "type": "string",
         "minLength": 1,
         "maxLength": 250
      },
      "classification": { "enum": [ "layout-mapping" ] },
      "path" : { "type":  "string" },
      "type": {
         "type":  "object",
         "properties" : {
            "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
            "name" : { "type":  "string", "maxLength": 250 }
         },
         "additionalProperties": false
      },
      "creatorId": { "type": "string" },
      "created": { "type": "string", "format": "date-time" },
      "lastModifierId": { "type": "string" },
      "lastModified": { "type": "string", "format": "date-time" },
      "tags": {
         "type": "array",
         "items": {
            "type": "string"
         },
         "maxItems": 100,
         "uniqueItems": true
      },
      "mappings": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {
               "layoutMode": { "type":  "string", "minLength": 1, "maxLength": 100 },
               "defaultLayout": {
                  "type":  "object",
                  "properties" : {
                     "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
                     "name" : { "type":  "string", "maxLength": 250 }
                  },
                  "required": [ "id" ],
                  "additionalProperties": false
               },
               "layouts": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "id": { "type": "string", "minLength": 1, "maxLength": 100 },
                        "name": { "type": "string", "maxLength": 250 }
                     },
                     "required": [ "id" ],
                     "additionalProperties": false
                  },
                  "minItems": 1,
                  "maxItems": 50,
                  "uniqueItems": true
               }
            },
            "required": [ "defaultLayout", "layouts" ],
            "additionalProperties": false
         },
         "minItems": 1,
         "maxItems": 50,
         "uniqueItems": true
      }
   },
   "additionalProperties": false,
   "required": [
      "name",
      "type",
      "classification",
      "mappings"
   ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/sites-text-layout-mapping.json
{
  "id": "sites-text-layout-mapping",
  "rev": "1-e961c12ac165d0180d516012fa83920a",
  "name": "sitesTextLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "373c81a5-d86b-4740-8f11-62fcbccfca08"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "sites-text-layout"
      },
      "layouts": [
        {
          "id": "sites-text-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/carousel-list-mapping.json
{
  "id": "carousel-list-mapping",
  "rev": "1-64a90e6d701d6d5877419252f9f4a004",
  "name": "carouselListMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "9aeeecef-85ce-4d41-a797-1ad27735d0cb"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "carousel-list"
      },
      "layouts": [
        {
          "id": "carousel-list"
        },
        {
          "id": "gallery-list"
        },
        {
          "id": "vertical-list"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/page-layout-mapping.json
{
  "id": "page-layout-mapping",
  "rev": "3-8ec8e1b48b60186a119462baeefc2f6e",
  "name": "pageLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "5f53fa8b-c6bd-453b-9ff0-c011e3e3dcf0"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "page-layout"
      },
      "layouts": [
        {
          "id": "page-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/page-style-contribution-layout-mapping.json
{
  "id": "page-style-contribution-layout-mapping",
  "rev": "3-67fc038809ed01f4b7f90b79ce142319",
  "name": "pageStyleContributionLayoutMapping",
  "classification": "layout-mapping",
  "tags": [
    "sites-next"
  ],
  "type": {
    "id": "3a3726b8-e0b2-4f10-98ed-b1c82e851b99"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "page-style-contribution-layout"
      },
      "layouts": [
        {
          "id": "page-style-contribution-layout"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/standard-page-layout-mapping.json
{
  "id": "standard-page-layout-mapping",
  "rev": "1-504a5b1e2d84c97c2f2f7737b52605ca",
  "name": "standardPageLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "2af1d22a-fecf-41e1-a808-7301cb37b79f"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "standard-page-layout"
      },
      "layouts": [
        {
          "id": "standard-page-layout"
        },
        {
          "id": "standard-page-hero-2-blocks"
        },
        {
          "id": "standard-page-hero-4-blocks"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layout-mappings/form-component-layout-mapping.json
{
  "id": "form-component-layout-mapping",
  "rev": "2-1f1ba4e69db3d2e6639e4276cc65a7c0",
  "name": "formComponentLayoutMapping",
  "classification": "layout-mapping",
  "type": {
    "id": "7df801d8-1d55-4652-ac59-93589b032375",
    "name": "Form component"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "form-component-layout",
        "name": "One Column"
      },
      "layouts": [
        {
          "id": "form-component-layout",
          "name": "One Column"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/data-basic-building-blocks/data/layout-mappings/sites-alignment-layout-mapping.json
{
  "name": "sitesAlignmentLayoutMapping",
  "id": "sites-alignment-layout-mapping",
  "classification": "layout-mapping",
  "mappings": [
    {
      "defaultLayout": {
        "name": "sitesAlignmentLayout",
        "id": "sites-alignment-layout"
      },
      "layouts": [
        {
          "name": "sitesAlignmentLayout",
          "id": "sites-alignment-layout"
        }
      ]
    }
  ],
  "tags": [
    "sites-next"
  ],
  "type": {
    "name": "Sites Alignment",
    "id": "d0cf6fd8-e061-4bd6-8f62-fd3ea795b4e5"
  },
  "rev": "0-a109af31-94f0-4d64-aca6-a132b1c436f1"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layout-mappings/Email-layout-mapping.json
{
  "id": "c380f30a-0152-4c8c-8894-b216acf89530",
  "rev": "1-93729695dea39f25a0fe8b46f4566947",
  "name": "Email Layout Mapping",
  "classification": "layout-mapping",
  "type": {
    "id": "51071056-1f70-499e-9ee3-b2066f56b119"
  },
  "mappings": [
    {
      "defaultLayout": {
        "id": "d8f3731d-4b51-4fef-a9b0-662ae824d8af"
      },
      "layouts": [
        {
          "id": "d8f3731d-4b51-4fef-a9b0-662ae824d8af"
        }
      ]
    }
  ]
}
