=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/layout-schema.json
{
  "id": "http://www.ibm.com/schemas/layout-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Layout Schema",
  "description": "Schema for Layout",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
      "maxLength": 100
    },
    "rev": {"type": "string" },
    "_revisions": { "type": "object" },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 250
    },
    "path" : { "type":  "string" },
    "description": {"type": "string", "maxLength": 500 },
    "classification": {"enum": [ "layout" ] },
    "creatorId": {"type": "string"},
    "created": {"type": "string", "format": "date-time" },
    "lastModifierId": {"type": "string"},
    "lastModified": {"type": "string", "format": "date-time" },
    "thumbnail": {
      "type":  "object",
      "properties" : {
        "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
        "path" : { "type":  "string" },
        "url" : { "type":  "string" }
      },
      "additionalProperties": false
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 100,
      "uniqueItems": true
    },
    "template": { "type": "string", "minLength" : 1 },
    "templateType": {
      "enum": [
        "handlebars",
        "angular"
      ]
    },
    "prerender": {
      "type": "boolean"
    },
    "urlTemplate": { "type": "string" }
  },
  "required": ["name", "classification", "template"],
  "additionalProperties": false
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/markup-renderer/layouts/sites-navigation-layout.json
{
  "id": "sites-navigation-layout",
  "rev": "10-83e82a56b54f28356c2d41d5b4170f72",
  "name": "siteNavigationLayout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/sites-navigation-layout.jpg"
  },
  "template": "/dxdam/templates/sites-navigation-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/sites/sites-navigation/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/layouts/button-component-layout.json
{
  "id": "button-component-layout",
  "rev": "4-94c0b30d842ae06bc97d98c5c2285373",
  "name": "buttonComponentLayout",
  "classification": "layout",
  "prerender": true,
  "template": "/email/components/button-component-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "/emails/{name}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/email-content.json
{
  "id": "713fbab1-acd2-426b-b190-47abcf9be37e",
  "rev": "1-45d631da7e48535be9314fdf82d31b43",
  "name": "Email Content",
  "classification": "layout",
  "prerender": false,
  "template": "/email/email-content.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/email-content/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/html-email-layout.json
{
  "id": "7c5c6e04-6777-4757-a703-7644d4d81c25",
  "rev": "1-39e983fb369afd523629ddf07106b9d2",
  "name": "HTML Email Layout",
  "classification": "layout",
  "prerender": false,
  "template": "/email/html-email-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/html-email-layout/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/form-component-layout.json
{
  "id": "form-component-layout",
  "rev": "1-2928112add43769d6163adcfd76928cb",
  "name": "One Column",
  "classification": "layout",
  "prerender": false,
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/form-component-layout.jpg"
  },
  "template": "form-component-layout",
  "templateType": "angular"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/stuart/layouts/standard-page-layout.json
{
  "id": "standard-page-layout",
  "rev": "1-60f74d059f2e4a9ae166c34fce03291e",
  "name": "One column",
  "classification": "layout",
  "prerender": false,
  "thumbnail": {
    "path": "/layouts/thumbnails/standard-page-hero_220.svg"
  },
  "template": "standard-page-layout",
  "templateType": "angular"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/stuart/layouts/all-types-page-hero-4-blocks.json
{
  "id": "all-types-page-hero-4-blocks",
  "rev": "1-ba772d64ed75de0520a791ef5fb2dd99",
  "name": "Five blocks",
  "classification": "layout",
  "prerender": false,
  "thumbnail": {
    "path": "/layouts/thumbnails/standard-page-hero-4-blocks_220.svg"
  },
  "template": "all-types-page-hero-4-blocks",
  "templateType": "angular"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/promotion-component-layout.json
{
  "id": "promotion-component-layout",
  "rev": "1-fd75247c16abc74529a78a7ba27bcf8a",
  "name": "promotionComponentLayout",
  "classification": "layout",
  "prerender": true,
  "template": "/email/components/promotion-component-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "/emails/{name}.html"
}
