=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/layout-schema.json
{
  "id": "http://www.ibm.com/schemas/layout-schema.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Layout Schema",
  "description": "Schema for Layout",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
      "maxLength": 100
    },
    "rev": {"type": "string" },
    "_revisions": { "type": "object" },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 250
    },
    "path" : { "type":  "string" },
    "description": {"type": "string", "maxLength": 500 },
    "classification": {"enum": [ "layout" ] },
    "creatorId": {"type": "string"},
    "created": {"type": "string", "format": "date-time" },
    "lastModifierId": {"type": "string"},
    "lastModified": {"type": "string", "format": "date-time" },
    "thumbnail": {
      "type":  "object",
      "properties" : {
        "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
        "path" : { "type":  "string" },
        "url" : { "type":  "string" }
      },
      "additionalProperties": false
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 100,
      "uniqueItems": true
    },
    "template": { "type": "string", "minLength" : 1 },
    "templateType": {
      "enum": [
        "handlebars",
        "angular"
      ]
    },
    "prerender": {
      "type": "boolean"
    },
    "urlTemplate": { "type": "string" }
  },
  "required": ["name", "classification", "template"],
  "additionalProperties": false
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/site-layout.json
{
  "id": "site-layout",
  "rev": "3-c1d8c40931a93ceb401ca08af5ef5ed7",
  "name": "siteLayout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/site-layout.jpg"
  },
  "template": "/sites/templates/site-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/sites/site-layout/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-layouts/data/layouts/page-style-contribution-layout.json
{
  "id": "page-style-contribution-layout",
  "rev": "3-fb9ff71bf874f69e964bdf9ae8c46da4",
  "name": "pageStyleContributionLayout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/page-contributions-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_63b3f57e91735eaa985f3ace1e44f38a"
  },
  "template": "/sites/templates/page-style-contribution-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/sites/page-styke-contribution/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/layouts/Email-Section-layout.json
{
  "id": "17375714-5c1a-4f82-91d2-7edd6f5b7747",
  "rev": "1-f5113c3d8ba39bc031a1f63d96518dcb",
  "name": "Email Section Layout",
  "classification": "layout",
  "prerender": false,
  "template": "/email/Email-Section-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/Email-Section-layout/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/layouts/sites-background-layout.json
{
  "name": "sitesBackgroundLayout",
  "id": "sites-background-layout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next"
  ],
  "template": "/dxdam/templates/sites-background-layout.hbs",
  "templateType": "handlebars",
  "thumbnail": {
    "path": "/dxauth/thumbnails/layouts/sites-background-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_752c49478323083eb44023d10c97603e"
  },
  "urlTemplate": "{templateLocation}/sites-background-layout/{id}.html",
  "rev": "0-a9a86bfb-bfc9-4ec4-a0fa-7aa6d09eebe9"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-types/data/layouts/sites-layout.json
{
  "name": "siteLayout",
  "id": "sites-layout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "template": "/dxdam/templates/sites-layout.hbs",
  "templateType": "handlebars",
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/sites-layout.jpg"
  },
  "urlTemplate": "{templateLocation}/sites/sites-layout/{id}.html",
  "rev": "0-58fa3a3a-6510-4de0-80a9-49bf679a3b5d"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-layouts/data/layouts/page-markup-contribution-layout.json
{
  "id": "page-markup-contribution-layout",
  "rev": "3-0d2b7daa7c6cfeacdd9daac80bd97b09",
  "name": "pageMarkupContributionLayout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next",
    "mode:head",
    "mode:body"
  ],
  "thumbnail": {
    "path": "/dxauth/layoutThumbs/page-contributions-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_63b3f57e91735eaa985f3ace1e44f38a"
  },
  "template": "/sites/templates/page-markup-contribution-layout.hbs",
  "templateType": "handlebars",
  "urlTemplate": "{templateLocation}/sites/page-markup-contribution/{id}.html"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/layouts/sites-image-layout.json
{
  "name": "sitesImageLayout",
  "id": "sites-image-layout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next"
  ],
  "template": "/dxdam/templates/sites-image-layout.hbs",
  "templateType": "handlebars",
  "thumbnail": {
    "path": "/dxauth/thumbnails/layouts/sites-image-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_ee3740277ba29d08b89da87a48a9dde0"
  },
  "urlTemplate": "{templateLocation}/sites/{id}.html",
  "rev": "0-6eca13a9-bb7c-4690-a765-3b0fbebdbdec"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/data-basic-building-blocks/data/layouts/sites-content-layout.json
{
  "name": "sitesContentLayout",
  "id": "sites-content-layout",
  "classification": "layout",
  "prerender": false,
  "tags": [
    "sites-next"
  ],
  "template": "/templates/sites-content-layout.hbs",
  "templateType": "handlebars",
  "thumbnail": {
    "path": "/dxauth/thumbnails/layouts/sites-content-layout.jpg",
    "url": "/authoring/v1/resources/a9b7575381cd03962dbe81e4116c8663_723ce97b348d8c79a8e33d1d6f2525e8"
  },
  "urlTemplate": "{templateLocation}/sites/{id}.html",
  "rev": "0-76925f6f-3a2d-4a03-88bf-c70be32a19ca"
}
