=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/type-schema.json
{
   "id": "http://www.ibm.com/schemas/type-schema.json",
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Content Type Schema",
   "description": "Schema for blank content type",
   "type": "object",
   "properties": {
      "id": {
         "type": "string",
         "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
         "maxLength": 100
      },
      "rev": {
         "type": "string"
      },
      "_revisions": { "type": "object" },
      "name": {
         "type": "string",
         "minLength": 1,
         "maxLength": 250
      },
      "path" : { "type":  "string" },
      "classification": {
         "enum": [ "content-type" ]
      },
      "description": {
         "type": "string",
         "maxLength": 500
      },
      "kind" : {
         "type": "array",
         "items": {
            "type": "string"
         },
         "uniqueItems": true
      },
      "thumbnail": {
         "type":  "object",
         "properties" : {
            "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
            "path" : { "type":  "string" },
            "url" : { "type":  "string" }
         },
         "additionalProperties": false
      },
      "contentThumbnail": {
         "type": "object",
         "properties": {
            "source": { "enum": [ "imageElementOrType", "imageElement", "type", "none" ]},
            "imageElement": { "type": "string",  "maxLength": 100}
         },
         "required": [ "source" ],
         "additionalProperties": false
      },
      "creatorId": {
         "type": "string"
      },
      "created": {
         "type": "string",
         "format": "date-time"
      },
      "lastModifierId": {
         "type": "string"
      },
      "lastModified": {
         "type": "string",
         "format": "date-time"
      },
      "linkedDocId": {
         "type": "string",
         "maxLength": 100
      },
      "tags": {
         "type": "array",
         "items": {
            "type": "string"
         },
         "maxItems": 100,
         "uniqueItems": true
      },
      "categoryIds": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "categories": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "status": {
         "enum": [
            "draft",
            "ready",
            "retired"
         ]
      },
      "elements": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {}
         }
      },
      "uiExtensions": {
         "type": "object",
         "properties": {
            "element": { "type": "string" },
            "elementBuiltin": { "type": "string" },
            "elementConfig": { "type": "object" }
         },
         "additionalProperties": false
      },
      "icon": {
         "enum": [
            "category",
            "group",
            "datetime",
            "formattedtext",
            "file",
            "image",
            "link",
            "location",
            "number",
            "reference",
            "optionselection",
            "text",
            "toggle",
            "variabletype",
            "video"
         ]
      }
   },
   "additionalProperties": false,
   "required": [
      "name",
      "classification",
      "status",
      "elements"
   ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/types/Sites-Navigation-Component.json
{
  "name": "Sites Navigation Component",
  "description": "",
  "id": "6854f419-3b8b-4410-8d33-134a485d05a3",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "number",
      "fieldType": "integer",
      "key": "startingWithNavigationLevel",
      "label": "Starting with Navigation Level",
      "required": true
    },
    {
      "elementType": "number",
      "fieldType": "integer",
      "key": "numberOfNavigationLevels",
      "label": "Number of Navigation Levels",
      "required": true
    }
  ],
  "kind": [
    "embedded"
  ],
  "status": "ready",
  "tags": [],
  "rev": "0-054617e6-77c8-46cc-9470-d2503884beb7"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Email-Content.json
{
  "id": "4cd0fbbb-3bf8-4497-9ee9-c89e37737674",
  "rev": "1-44471042d98c6017dcf21338f0dc4024",
  "name": "Email Content",
  "classification": "content-type",
  "kind": [
    "embedded"
  ],
  "description": "",
  "status": "ready",
  "tags": [],
  "elements": [
    {
      "elementType": "group",
      "typeRef": {
        "id": "b201f69e-29ff-4f3e-9a72-6c6be6c7d754"
      },
      "label": "button",
      "key": "button"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "251f4c19-ea42-4e4d-8831-1ffca17d6a6d"
      },
      "label": "divider",
      "key": "divider"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "aa358e28-2e60-416a-97d7-d1a6dd5e165b"
      },
      "label": "html",
      "key": "html"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "b7b05524-87ed-4509-b6fb-972f2cbf26d5"
      },
      "label": "image",
      "key": "image"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "4e70d4a0-0112-43c5-887b-dde336ebe678"
      },
      "label": "image and text",
      "key": "imageAndText"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "7952a5b2-57d0-4a1b-a008-d37c7d7f5261"
      },
      "label": "image group",
      "key": "imageGroup"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "e98ba889-d5e4-4b9b-8c42-e3a5c35a10d3"
      },
      "label": "promotion",
      "key": "promotion"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "8bb7f03c-23a2-46c5-bd15-fbf4d1e8bd4f"
      },
      "label": "social follow",
      "key": "socialFollow"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "209c5579-4e6d-4e88-9c47-76de4c25c6f8"
      },
      "label": "spacer",
      "key": "spacer"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "09ed64f3-23d9-48bb-871d-e00430751ea6"
      },
      "label": "text",
      "key": "text"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "98bec4ac-6170-402c-9405-6e8cfd99508a"
      },
      "label": "Link bar",
      "key": "linkBar"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "7f81225a-8827-43d1-9d52-5f83eb6ee54f"
      },
      "label": "video",
      "key": "video"
    },
    {
      "elementType": "reference",
      "label": "reference",
      "key": "reference"
    },
    {
      "elementType": "optionselection",
      "options": [
        {
          "label": "Button",
          "selection": "button"
        },
        {
          "label": "Divider",
          "selection": "divider"
        },
        {
          "label": "HTML",
          "selection": "html"
        },
        {
          "label": "Image",
          "selection": "image"
        },
        {
          "label": "Image and Text",
          "selection": "imageAndText"
        },
        {
          "label": "Image Group",
          "selection": "imageGroup"
        },
        {
          "label": "Promotion",
          "selection": "promotion"
        },
        {
          "label": "Social Follow",
          "selection": "socialFollow"
        },
        {
          "label": "Spacer",
          "selection": "spacer"
        },
        {
          "label": "Text",
          "selection": "text"
        },
        {
          "label": "Link bar",
          "selection": "linkBar"
        },
        {
          "label": "Video",
          "selection": "video"
        },
        {
          "label": "Reference",
          "selection": "reference"
        }
      ],
      "required": true,
      "label": "selected",
      "key": "selected"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Hero-video.json
{
  "id": "a47af09a-9315-4a01-ad30-cd998d341b0b",
  "rev": "1-5205468e32c52e5cca7d0115e8a87d0d",
  "name": "Hero video",
  "classification": "content-type",
  "kind": [
    "standalone"
  ],
  "thumbnail": {
    "id": "652c4957-1636-405a-8604-71b22181deda"
  },
  "contentThumbnail": {
    "imageElement": "",
    "source": "imageElementOrType"
  },
  "description": "",
  "status": "ready",
  "tags": [
    "oslo",
    "IBM sample"
  ],
  "elements": [
    {
      "elementType": "video",
      "fieldLabel": "Video",
      "label": "Video",
      "key": "video"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Sites-Promotion.json
{
  "id": "0b1c47a9-eb31-49ec-8fd7-89ca21a36b36",
  "rev": "24-f44ddd8aeba2762fc17ec237b27ded60",
  "name": "Sites Promotion",
  "classification": "content-type",
  "kind": [
    "standalone",
    "embedded"
  ],
  "description": "",
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "elements": [
    {
      "elementType": "group",
      "typeRef": {
        "id": "0a92059b-de6b-476d-b291-1638a435d0af"
      },
      "label": "Background",
      "key": "background"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      },
      "label": "Margin",
      "key": "margin"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "373c81a5-d86b-4740-8f11-62fcbccfca08"
      },
      "label": "Text",
      "key": "text"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "c8295d37-7235-495e-8d40-f3b8bafe4099"
      },
      "label": "Image",
      "key": "image"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "dee92057-69e3-489b-b13b-15f9b28770a1"
      },
      "label": "Button",
      "key": "button"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      },
      "label": "Common Settings",
      "key": "commonSettings"
    },
    {
      "elementType": "optionselection",
      "options": [
        {
          "label": "Image Left",
          "selection": "image-left"
        },
        {
          "label": "Image Right",
          "selection": "image-right"
        },
        {
          "label": "Image Top",
          "selection": "image-top"
        }
      ],
      "label": "Layout",
      "key": "layout"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-email/data/types/Promotion.json
{
  "id": "e98ba889-d5e4-4b9b-8c42-e3a5c35a10d3",
  "rev": "8-30d30c845aa30be322092aca53ccdc68",
  "name": "Promotion",
  "classification": "content-type",
  "kind": [
    "standalone",
    "embedded"
  ],
  "description": "",
  "status": "ready",
  "tags": [],
  "elements": [
    {
      "elementType": "group",
      "typeRef": {
        "id": "8c4a8b02-67a1-4849-8e2d-f90be58485c5",
        "name": "Background Extension"
      },
      "label": "Background",
      "key": "background"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "9c5e08f5-e54d-42c4-b855-c73eb0908022",
        "name": "Boundary options"
      },
      "label": "Margin",
      "key": "margins"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "f71e2d31-6536-4016-9f89-c6848d0f4b55",
        "name": "Text Group"
      },
      "label": "Text",
      "key": "textGroup"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "39bd65fc-2733-4c8a-a700-3075f127fb2d",
        "name": "Custom ImageGroup"
      },
      "label": "Image",
      "key": "imageGroup"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "2d9f0c5e-8a89-4b8c-abfc-7d2de4f623dd",
        "name": "Button Group"
      },
      "label": "Button",
      "key": "buttonGroup"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "eeff476e-0559-444f-97d1-486a10a86b80",
        "name": "Common settings"
      },
      "label": "Common Settings",
      "key": "commonSettings"
    },
    {
      "elementType": "optionselection",
      "options": [
        {
          "label": "Image Left",
          "selection": "image-left"
        },
        {
          "label": "Image Right",
          "selection": "image-right"
        },
        {
          "label": "Image Top",
          "selection": "image-top"
        }
      ],
      "label": "Layout",
      "key": "layout"
    },
    {
      "elementType": "text",
      "label": "Key",
      "key": "key"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/types/Sites-Text.json
{
  "name": "Sites Text",
  "description": "",
  "id": "373c81a5-d86b-4740-8f11-62fcbccfca08",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "formattedtext",
      "key": "text",
      "label": "text",
      "placeholder": {
        "show": true,
        "text": "Text"
      }
    },
    {
      "elementType": "group",
      "key": "textStyle",
      "label": "Text Style",
      "typeRef": {
        "name": "Sites Styling",
        "id": "cfa7081a-921d-4f50-a543-027b983b01b5"
      }
    },
    {
      "elementType": "group",
      "key": "linkColor",
      "label": "Link Color",
      "typeRef": {
        "name": "Sites Color",
        "id": "93ed78a8-cea7-4188-8584-a8bedca6ebac"
      }
    },
    {
      "elementType": "group",
      "key": "background",
      "label": "Background",
      "typeRef": {
        "name": "Sites Background",
        "id": "0a92059b-de6b-476d-b291-1638a435d0af"
      }
    },
    {
      "elementType": "group",
      "key": "alignment",
      "label": "Alignment",
      "typeRef": {
        "name": "Sites Alignment",
        "id": "d0cf6fd8-e061-4bd6-8f62-fd3ea795b4e5"
      }
    },
    {
      "elementType": "group",
      "key": "lineHeight",
      "label": "Line Height",
      "typeRef": {
        "name": "Sites Line Height",
        "id": "e5e97340-b03b-42ea-9d03-f8bc214f42b0"
      }
    },
    {
      "elementType": "group",
      "key": "padding",
      "label": "Padding",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "margin",
      "label": "Margin",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "commonSettings",
      "label": "Common Settings",
      "typeRef": {
        "name": "Sites Common Settings",
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      }
    },
    {
      "elementType": "text",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": [
    "standalone",
    "embedded"
  ],
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "rev": "0-2462bdc9-04e6-43fe-a213-2fee3c4fe665"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Sites-Navigation.json
{
  "id": "843fb991-7413-4517-bfcb-b59fc4b1f449",
  "rev": "10-5a5d255fa9a45f1a714bd071a09e5a99",
  "name": "Sites Navigation",
  "classification": "content-type",
  "kind": [
    "embedded",
    "standalone"
  ],
  "description": "",
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "elements": [
    {
      "elementType": "text",
      "label": "Navigation",
      "key": "navigation",
      "required": true,
      "displayType": "multiLine"
    },
    {
      "elementType": "text",
      "label": "Default Page",
      "key": "defaultPage"
    },
    {
      "elementType": "text",
      "label": "Key",
      "key": "key"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/types/Sites-Color.json
{
  "name": "Sites Color",
  "description": "",
  "id": "93ed78a8-cea7-4188-8584-a8bedca6ebac",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "text",
      "key": "colorCode",
      "label": "Color code"
    },
    {
      "elementType": "text",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": [
    "embedded"
  ],
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "rev": "0-04f2bec4-3937-4364-9425-a33ff3de8cc6"
}
