=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/type-schema.json
{
   "id": "http://www.ibm.com/schemas/type-schema.json",
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Content Type Schema",
   "description": "Schema for blank content type",
   "type": "object",
   "properties": {
      "id": {
         "type": "string",
         "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
         "maxLength": 100
      },
      "rev": {
         "type": "string"
      },
      "_revisions": { "type": "object" },
      "name": {
         "type": "string",
         "minLength": 1,
         "maxLength": 250
      },
      "path" : { "type":  "string" },
      "classification": {
         "enum": [ "content-type" ]
      },
      "description": {
         "type": "string",
         "maxLength": 500
      },
      "kind" : {
         "type": "array",
         "items": {
            "type": "string"
         },
         "uniqueItems": true
      },
      "thumbnail": {
         "type":  "object",
         "properties" : {
            "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
            "path" : { "type":  "string" },
            "url" : { "type":  "string" }
         },
         "additionalProperties": false
      },
      "contentThumbnail": {
         "type": "object",
         "properties": {
            "source": { "enum": [ "imageElementOrType", "imageElement", "type", "none" ]},
            "imageElement": { "type": "string",  "maxLength": 100}
         },
         "required": [ "source" ],
         "additionalProperties": false
      },
      "creatorId": {
         "type": "string"
      },
      "created": {
         "type": "string",
         "format": "date-time"
      },
      "lastModifierId": {
         "type": "string"
      },
      "lastModified": {
         "type": "string",
         "format": "date-time"
      },
      "linkedDocId": {
         "type": "string",
         "maxLength": 100
      },
      "tags": {
         "type": "array",
         "items": {
            "type": "string"
         },
         "maxItems": 100,
         "uniqueItems": true
      },
      "categoryIds": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "categories": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "status": {
         "enum": [
            "draft",
            "ready",
            "retired"
         ]
      },
      "elements": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {}
         }
      },
      "uiExtensions": {
         "type": "object",
         "properties": {
            "element": { "type": "string" },
            "elementBuiltin": { "type": "string" },
            "elementConfig": { "type": "object" }
         },
         "additionalProperties": false
      },
      "icon": {
         "enum": [
            "category",
            "group",
            "datetime",
            "formattedtext",
            "file",
            "image",
            "link",
            "location",
            "number",
            "reference",
            "optionselection",
            "text",
            "toggle",
            "variabletype",
            "video"
         ]
      }
   },
   "additionalProperties": false,
   "required": [
      "name",
      "classification",
      "status",
      "elements"
   ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/data-basic-building-blocks/data/types/Sites-Promotion.json
{
  "name": "Sites Promotion",
  "description": "This block represents a promotion item to be rendered on a page. A promotion is comprised by an image, a text, and a clickable button.",
  "id": "0b1c47a9-eb31-49ec-8fd7-89ca21a36b36",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "group",
      "key": "background",
      "helpText": "This element controls the background for this promotion block.",
      "label": "Background",
      "typeRef": {
        "name": "Sites Background",
        "id": "0a92059b-de6b-476d-b291-1638a435d0af"
      }
    },
    {
      "elementType": "group",
      "key": "margin",
      "helpText": "This element controls the margin values for this promotion block.",
      "label": "Margin",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "text",
      "helpText": "This element holds the actual text data for this promotion block.",
      "label": "Text",
      "typeRef": {
        "name": "Sites Text",
        "id": "373c81a5-d86b-4740-8f11-62fcbccfca08"
      }
    },
    {
      "elementType": "group",
      "key": "image",
      "helpText": "This element holds the image for this promotion block.",
      "label": "Image",
      "typeRef": {
        "name": "Sites Image",
        "id": "c8295d37-7235-495e-8d40-f3b8bafe4099"
      }
    },
    {
      "elementType": "group",
      "key": "button",
      "helpText": "This element controls the button for this promotion block.",
      "label": "Button",
      "typeRef": {
        "name": "Sites Button",
        "id": "dee92057-69e3-489b-b13b-15f9b28770a1"
      }
    },
    {
      "elementType": "group",
      "key": "commonSettings",
      "helpText": "This element controls the common settings for this block.",
      "label": "Common Settings",
      "typeRef": {
        "name": "Sites Common Settings",
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      }
    },
    {
      "elementType": "optionselection",
      "key": "layout",
      "helpText": "This element controls the layout to be applied to this promotion block.",
      "label": "Layout",
      "options": [
        {
          "label": "Image Left",
          "selection": "image-left"
        },
        {
          "label": "Image Right",
          "selection": "image-right"
        },
        {
          "label": "Image Top",
          "selection": "image-top"
        }
      ]
    },
    {
      "elementType": "text",
      "helpText": "This element is used to uniquely identify this element in the current content item",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": ["standalone", "embedded"],
  "status": "ready",
  "tags": ["sites-next"],
  "rev": "0-b7cf0430-1ee6-4c32-ac0f-8308c3f85970"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/types/Sites-Social-Link.json
{
  "name": "Sites Social Link",
  "description": "",
  "id": "98f24456-bf11-4248-bca9-07e273b8dbc4",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "text",
      "key": "icon",
      "label": "Icon"
    },
    {
      "elementType": "link",
      "key": "url",
      "label": "URL"
    },
    {
      "elementType": "text",
      "key": "alttext",
      "label": "Alt text"
    },
    {
      "elementType": "text",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": [
    "embedded"
  ],
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "rev": "0-aacf3bd2-2dac-4eb8-aab1-5b891e225a44"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/data/types/Event.json
{
  "id": "10ed9f3f-ab41-45a9-ba24-d988974affa7",
  "rev": "2-8ac06483b4706438aed0fa2b7144217e",
  "name": "Event",
  "classification": "content-type",
  "kind": [
    "standalone"
  ],
  "thumbnail": {
    "id": "9c6440b5-512c-4cfc-9941-b1ad759f77f5",
    "path": "/dxdam/9c/9c6440b5-512c-4cfc-9941-b1ad759f77f5/events_icon_220.png",
    "url": "/authoring/v1/resources/b05c661d5e891602477ea9714733a975"
  },
  "contentThumbnail": {
    "imageElement": "",
    "source": "imageElementOrType"
  },
  "description": "Content created from this template is included on the events page in the Oslo site.",
  "status": "ready",
  "tags": [
    "oslo",
    "IBM sample"
  ],
  "elements": [
    {
      "elementType": "text",
      "fieldLabel": "Text",
      "label": "Event title",
      "key": "heading",
      "placeholder": {
        "show": true,
        "text": "Event title"
      }
    },
    {
      "elementType": "datetime",
      "fieldLabel": "Date",
      "label": "Event date",
      "key": "date"
    },
    {
      "elementType": "formattedtext",
      "fieldLabel": "Formatted Text",
      "label": "Event description",
      "key": "body",
      "placeholder": {
        "show": true,
        "text": "Tell us about your event and who should attend."
      }
    },
    {
      "elementType": "formattedtext",
      "fieldLabel": "Formatted Text",
      "label": "Event details",
      "key": "eventDetails",
      "placeholder": {
        "show": true,
        "text": "Reel in your audience with more details about the event."
      }
    },
    {
      "elementType": "formattedtext",
      "fieldLabel": "Formatted Text",
      "label": "Event location",
      "key": "eventLocation",
      "placeholder": {
        "show": true,
        "text": "Add the event location. "
      }
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Social-icon.json
{
  "id": "d5f01209-aa97-4118-81e2-fa26932e63af",
  "rev": "1-8dbc3d43303388638c32d7848d14f589",
  "name": "Social icon",
  "classification": "content-type",
  "kind": [
    "embedded"
  ],
  "contentThumbnail": {
    "imageElement": "icon",
    "source": "imageElementOrType"
  },
  "description": "",
  "status": "ready",
  "tags": [],
  "elements": [
    {
      "elementType": "image",
      "label": "Icon",
      "key": "icon"
    },
    {
      "elementType": "number",
      "fieldType": "integer",
      "label": "Size",
      "key": "size"
    },
    {
      "elementType": "link",
      "label": "LinkURL",
      "key": "linkurl"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next/types/Sites-Image.json
{
  "name": "Sites Image",
  "description": "",
  "id": "c8295d37-7235-495e-8d40-f3b8bafe4099",
  "classification": "content-type",
  "contentThumbnail": {
    "imageElement": "image",
    "source": "imageElementOrType"
  },
  "elements": [
    {
      "acceptType": [
        "jpg",
        "jpeg",
        "png",
        "gif"
      ],
      "elementType": "image",
      "key": "image",
      "label": "Image"
    },
    {
      "elementType": "group",
      "key": "alignment",
      "label": "Alignment",
      "typeRef": {
        "name": "Sites Alignment",
        "id": "d0cf6fd8-e061-4bd6-8f62-fd3ea795b4e5"
      }
    },
    {
      "elementType": "group",
      "key": "padding",
      "label": "Padding",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "margin",
      "label": "Margin",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "commonSettings",
      "label": "Common Settings",
      "typeRef": {
        "name": "Sites Common Settings",
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      }
    },
    {
      "elementType": "text",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": [
    "standalone",
    "embedded"
  ],
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "rev": "0-994eafcc-4c98-4ae0-9a9a-61fd7462060e"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Page-Profile.json
{
  "id": "c6164ac9-90c5-4d23-8dbf-8378343512b3",
  "rev": "1-225827e606d6d3ba6a692f918c956623",
  "name": "Page Profile",
  "classification": "content-type",
  "kind": [
    "standalone"
  ],
  "description": "Set of markup contributions for a page, organized by contributions for the head and the body section.",
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "elements": [
    {
      "elementType": "reference",
      "label": "contributions",
      "key": "contributions",
      "allowMultipleValues": true,
      "minimumValues": 0,
      "fieldLabel": "Content item",
      "role": [
        "configuration"
      ],
      "restrictTypes": [
        {
          "id": "aab86460-0018-44c2-9f52-3a326e58f7f7"
        }
      ]
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-email/data/types/Font-options.json
{
  "id": "f8253f3b-1a03-4d08-99e0-9723bb4ca3a8",
  "rev": "6-32a578fb00f16cf4aa2e6eaeb723c7fc",
  "name": "Font options",
  "classification": "content-type",
  "kind": [
    "embedded"
  ],
  "description": "",
  "status": "ready",
  "tags": [],
  "elements": [
    {
      "elementType": "optionselection",
      "options": [
        {
          "label": "Arial",
          "selection": "Arial"
        },
        {
          "label": "Comic Sans MS",
          "selection": "Comic Sans MS"
        },
        {
          "label": "Courier New",
          "selection": "Courier New"
        },
        {
          "label": "Georgia",
          "selection": "Georgia"
        },
        {
          "label": "Lucida Sans Unicode",
          "selection": "Lucida Sans Unicode"
        },
        {
          "label": "Tahoma",
          "selection": "Tahoma"
        },
        {
          "label": "Times New Roman",
          "selection": "Times New Roman"
        },
        {
          "label": "Trebuchet MS",
          "selection": "Trebuchet MS"
        },
        {
          "label": "Verdana",
          "selection": "Verdana"
        }
      ],
      "label": "Fonts",
      "key": "fonts"
    },
    {
      "elementType": "text",
      "label": "Key",
      "key": "key"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Background-Image.json
{
  "id": "0c6b2078-02dd-4c5d-858f-99d6d88114b5",
  "rev": "1-51b1139b659892069186b7a0f13bc6fb",
  "name": "Background Image",
  "classification": "content-type",
  "kind": [
    "embedded"
  ],
  "contentThumbnail": {
    "imageElement": "image",
    "source": "imageElementOrType"
  },
  "description": "",
  "status": "ready",
  "tags": [],
  "elements": [
    {
      "elementType": "toggle",
      "label": "Include background image",
      "key": "includeBackgroundImage"
    },
    {
      "elementType": "image",
      "label": "Image",
      "key": "image"
    },
    {
      "elementType": "optionselection",
      "options": [
        {
          "label": "Full Width",
          "selection": "full-width"
        },
        {
          "label": "Center",
          "selection": "center"
        },
        {
          "label": "Tile",
          "selection": "tile"
        }
      ],
      "label": "Fill options",
      "key": "fillOptions"
    }
  ]
}
