=== acoustic-content-samples/prod-wch-sdk-ng9/packages/api/src/schema/com/ibm/dx/authoring/common/validation/schemas/type-schema.json
{
   "id": "http://www.ibm.com/schemas/type-schema.json",
   "$schema": "http://json-schema.org/draft-04/schema#",
   "title": "Content Type Schema",
   "description": "Schema for blank content type",
   "type": "object",
   "properties": {
      "id": {
         "type": "string",
         "pattern": "^[a-zA-Z0-9*.\\-+_~$!',()]*$",
         "maxLength": 100
      },
      "rev": {
         "type": "string"
      },
      "_revisions": { "type": "object" },
      "name": {
         "type": "string",
         "minLength": 1,
         "maxLength": 250
      },
      "path" : { "type":  "string" },
      "classification": {
         "enum": [ "content-type" ]
      },
      "description": {
         "type": "string",
         "maxLength": 500
      },
      "kind" : {
         "type": "array",
         "items": {
            "type": "string"
         },
         "uniqueItems": true
      },
      "thumbnail": {
         "type":  "object",
         "properties" : {
            "id" : { "type":  "string", "minLength": 1, "maxLength": 100 },
            "path" : { "type":  "string" },
            "url" : { "type":  "string" }
         },
         "additionalProperties": false
      },
      "contentThumbnail": {
         "type": "object",
         "properties": {
            "source": { "enum": [ "imageElementOrType", "imageElement", "type", "none" ]},
            "imageElement": { "type": "string",  "maxLength": 100}
         },
         "required": [ "source" ],
         "additionalProperties": false
      },
      "creatorId": {
         "type": "string"
      },
      "created": {
         "type": "string",
         "format": "date-time"
      },
      "lastModifierId": {
         "type": "string"
      },
      "lastModified": {
         "type": "string",
         "format": "date-time"
      },
      "linkedDocId": {
         "type": "string",
         "maxLength": 100
      },
      "tags": {
         "type": "array",
         "items": {
            "type": "string"
         },
         "maxItems": 100,
         "uniqueItems": true
      },
      "categoryIds": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "categories": {
         "type": "array",
         "items": {
            "type": "string"
         }
      },
      "status": {
         "enum": [
            "draft",
            "ready",
            "retired"
         ]
      },
      "elements": {
         "type": "array",
         "items": {
            "type": "object",
            "properties": {}
         }
      },
      "uiExtensions": {
         "type": "object",
         "properties": {
            "element": { "type": "string" },
            "elementBuiltin": { "type": "string" },
            "elementConfig": { "type": "object" }
         },
         "additionalProperties": false
      },
      "icon": {
         "enum": [
            "category",
            "group",
            "datetime",
            "formattedtext",
            "file",
            "image",
            "link",
            "location",
            "number",
            "reference",
            "optionselection",
            "text",
            "toggle",
            "variabletype",
            "video"
         ]
      }
   },
   "additionalProperties": false,
   "required": [
      "name",
      "classification",
      "status",
      "elements"
   ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-generate-layouts/data/types/Sites-HTML.json
{
  "id": "85bdc88c-5b4c-4002-a665-37ba5bf95cb6",
  "rev": "16-ce3146791b564b45b5bcff551a0236ca",
  "name": "Sites HTML",
  "classification": "content-type",
  "kind": [
    "standalone",
    "embedded"
  ],
  "description": "",
  "status": "ready",
  "tags": [
    "sites-next"
  ],
  "elements": [
    {
      "elementType": "text",
      "label": "Code",
      "key": "code",
      "minLength": 1,
      "placeholder": {
        "show": true,
        "text": "Compose your HTML and Handlebar code here."
      },
      "displayType": "multiLine",
      "displayHeight": 30,
      "helpText": "Provide your custom HTML code here. You can also include handlebar references to the current rendering context."
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      },
      "label": "Padding",
      "key": "padding"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      },
      "label": "Margin",
      "key": "margin"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      },
      "label": "Common Settings",
      "key": "commonSettings"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/data-basic-building-blocks/data/types/Sites-Social-Follow.json
{
  "name": "Sites Social Follow",
  "description": "This block represents a clickable \"follow\" link to be rendered on the page",
  "id": "669768ce-44c7-4de3-83c1-a72d871e8df2",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "text",
      "key": "iconSet",
      "label": "Icon Set"
    },
    {
      "allowMultipleValues": true,
      "elementType": "group",
      "key": "socialLinks",
      "helpText": "This element controls the link icon and click target for this block.",
      "label": "Social Links",
      "required": false,
      "typeRef": {
        "name": "Sites Social Link",
        "id": "98f24456-bf11-4248-bca9-07e273b8dbc4"
      }
    },
    {
      "elementType": "number",
      "fieldType": "integer",
      "helpText": "This element controls the size of this block.",
      "key": "size",
      "label": "Size"
    },
    {
      "elementType": "group",
      "key": "backgroundColor",
      "helpText": "This element controls the background for this block.",
      "label": "Background Color",
      "typeRef": {
        "name": "Sites Color",
        "id": "93ed78a8-cea7-4188-8584-a8bedca6ebac"
      }
    },
    {
      "elementType": "group",
      "key": "alignment",
      "helpText": "This element controls the alignment definition for this block.",
      "label": "Alignment",
      "typeRef": {
        "name": "Sites Alignment",
        "id": "d0cf6fd8-e061-4bd6-8f62-fd3ea795b4e5"
      }
    },
    {
      "elementType": "number",
      "fieldType": "integer",
      "helpText": "This element controls the spacing to be added between clickable icons.",
      "key": "spacing",
      "label": "Spacing between iconsâ€‹"
    },
    {
      "elementType": "group",
      "key": "padding",
      "helpText": "This element controls the padding values for this block.",
      "label": "Padding",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "commonSettings",
      "helpText": "This element controls the common settings for this block.",
      "label": "Common Settings",
      "typeRef": {
        "name": "Sites Common Settings",
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      }
    },
    {
      "elementType": "text",
      "helpText": "This element is used to uniquely identify this element in the current content item",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": ["standalone", "embedded"],
  "status": "ready",
  "tags": ["sites-next"],
  "rev": "0-a0e5b4b0-cec1-4a17-b631-9b2280e4a823"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/data-basic-building-blocks/data/types/Sites-Link-Bar.json
{
  "name": "Sites Link Bar",
  "description": "This block represents a list of links to be rendered on a page",
  "id": "d0f831c3-1b0a-41ba-8a6b-10f2eca3789a",
  "classification": "content-type",
  "elements": [
    {
      "allowMultipleValues": true,
      "elementType": "link",
      "helpText": "This element controls the actual list of links for this link bar.",
      "fieldLabel": "Links",
      "key": "links",
      "label": "Links",
      "maximumValues": 7,
      "minimumValues": 2,
      "required": true
    },
    {
      "elementType": "group",
      "key": "textStyle",
      "helpText": "This element controls the text styling for this link bar.",
      "label": "Text Style",
      "typeRef": {
        "name": "Sites Styling",
        "id": "cfa7081a-921d-4f50-a543-027b983b01b5"
      }
    },
    {
      "elementType": "group",
      "key": "backgroundColor",
      "helpText": "This element controls the background color for this link bar.",
      "label": "Background Color",
      "typeRef": {
        "name": "Sites Color",
        "id": "93ed78a8-cea7-4188-8584-a8bedca6ebac"
      }
    },
    {
      "elementType": "group",
      "key": "alignment",
      "helpText": "This element controls the alignment defintion for this link bar.",
      "label": "Alignment",
      "typeRef": {
        "name": "Sites Alignment",
        "id": "d0cf6fd8-e061-4bd6-8f62-fd3ea795b4e5"
      }
    },
    {
      "elementType": "number",
      "fieldType": "integer",
      "helpText": "This element controls the spacing between links.",
      "key": "spacingBetweenLinks",
      "label": "Spacing between links"
    },
    {
      "elementType": "group",
      "key": "padding",
      "helpText": "This element controls the padding values for this link bar.",
      "label": "Padding",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "verticalRule",
      "label": "Vertical Rule",
      "helpText": "This element controls the vertical rules to be used by this link bar.",
      "typeRef": {
        "name": "Sites Vertical Rule",
        "id": "8e460c39-9cf6-4a78-9726-ee43ad961a8a"
      }
    },
    {
      "elementType": "group",
      "key": "commonSettings",
      "helpText": "This element controls the common settings for this link bar.",
      "label": "Common Settings",
      "typeRef": {
        "name": "Sites Common Settings",
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      }
    },
    {
      "elementType": "text",
      "helpText": "This element is used to uniquely identify this element in the current content item",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": ["standalone", "embedded"],
  "status": "ready",
  "tags": ["sites-next"],
  "rev": "0-8c8462e2-d19d-4a6d-b5b7-f7d1792a16d9"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/markup-renderer/types/Sites-Boundary.json
{
  "name": "Sites Boundary",
  "description": "This element controls the boundary dimensions to be used for padding/margin styling for a given block",
  "id": "d403f72d-5383-423c-ba33-5cedd61c9224",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "number",
      "helpText": "The value for the top boundary",
      "fieldType": "integer",
      "key": "top",
      "label": "Top",
      "minimum": 0
    },
    {
      "elementType": "number",
      "helpText": "The value for the bottom boundary",
      "fieldType": "integer",
      "key": "bottom",
      "label": "Bottom",
      "minimum": 0
    },
    {
      "elementType": "number",
      "helpText": "The value for the left boundary",
      "fieldType": "integer",
      "key": "left",
      "label": "Left",
      "minimum": 0
    },
    {
      "elementType": "number",
      "helpText": "The value for the right boundary",
      "fieldType": "integer",
      "key": "right",
      "label": "Right",
      "minimum": 0
    },
    {
      "elementType": "text",
      "helpText": "This element is used to uniquely identify this element in the current content item",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": ["embedded"],
  "status": "ready",
  "tags": ["sites-next"],
  "rev": "0-39142db7-686c-40de-87cc-f60e6012a6cd"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/proto-sites-next-app/data/types/Image.json
{
  "id": "b7b05524-87ed-4509-b6fb-972f2cbf26d5",
  "rev": "1-ced7651cf7e3a5ea563c60c4570907bb",
  "name": "Image",
  "classification": "content-type",
  "kind": [
    "standalone",
    "embedded"
  ],
  "contentThumbnail": {
    "imageElement": "image",
    "source": "imageElementOrType"
  },
  "description": "",
  "status": "ready",
  "tags": [
    "IBM email sample"
  ],
  "elements": [
    {
      "elementType": "image",
      "label": "Image",
      "key": "image",
      "acceptType": [
        "jpg",
        "jpeg",
        "png",
        "gif"
      ]
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "0915841f-cf93-4e3c-8ece-f22b0c41a9e6"
      },
      "label": "Alignment",
      "key": "align"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "9c5e08f5-e54d-42c4-b855-c73eb0908022"
      },
      "label": "Padding",
      "key": "padding"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "9c5e08f5-e54d-42c4-b855-c73eb0908022"
      },
      "label": "Margin",
      "key": "margin"
    },
    {
      "elementType": "group",
      "typeRef": {
        "id": "eeff476e-0559-444f-97d1-486a10a86b80"
      },
      "label": "Common Settings",
      "key": "commonSettings"
    }
  ]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/markup-renderer/types/Sites-HB-Text.json
{
  "name": "Sites HB Text",
  "description": "",
  "id": "ac299073-48a2-446d-987d-d893257abdb3",
  "classification": "content-type",
  "elements": [
    {
      "elementType": "formattedtext",
      "key": "text",
      "helpText": "The actual formatted text",
      "label": "text",
      "placeholder": {
        "show": true,
        "text": "Text"
      }
    },
    {
      "elementType": "group",
      "key": "textStyle",
      "helpText": "This element controls the text styling to be applied to this text block",
      "label": "Text Style",
      "typeRef": {
        "name": "Sites Styling",
        "id": "cfa7081a-921d-4f50-a543-027b983b01b5"
      }
    },
    {
      "elementType": "group",
      "key": "linkColor",
      "label": "Link Color",
      "helpText": "This element controls the color for the links contained in the text of this text block",
      "typeRef": {
        "name": "Sites Color",
        "id": "93ed78a8-cea7-4188-8584-a8bedca6ebac"
      }
    },
    {
      "elementType": "group",
      "key": "background",
      "label": "Background",
      "helpText": "This element controls the baground for this text block",
      "typeRef": {
        "name": "Sites Background",
        "id": "0a92059b-de6b-476d-b291-1638a435d0af"
      }
    },
    {
      "elementType": "group",
      "key": "alignment",
      "helpText": "This element controls the alignment defintion for this text block",
      "label": "Alignment",
      "typeRef": {
        "name": "Sites Alignment",
        "id": "d0cf6fd8-e061-4bd6-8f62-fd3ea795b4e5"
      }
    },
    {
      "elementType": "group",
      "key": "lineHeight",
      "helpText": "This element controls the line hight for this text block",
      "label": "Line Height",
      "typeRef": {
        "name": "Sites Line Height",
        "id": "e5e97340-b03b-42ea-9d03-f8bc214f42b0"
      }
    },
    {
      "elementType": "group",
      "key": "padding",
      "helpText": "This element controls the padding values for this text block",
      "label": "Padding",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "margin",
      "helpText": "This element controls the margin values for this text block",
      "label": "Margin",
      "typeRef": {
        "name": "Sites Boundary",
        "id": "d403f72d-5383-423c-ba33-5cedd61c9224"
      }
    },
    {
      "elementType": "group",
      "key": "commonSettings",
      "label": "Common Settings",
      "helpText": "This element controls the common settingsfor this text block",
      "typeRef": {
        "name": "Sites Common Settings",
        "id": "dba345e3-10a0-44ed-b0aa-6cffe74e1343"
      }
    },
    {
      "elementType": "text",
      "helpText": "This element is used to uniquely identify this element in the current content item",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": ["standalone", "embedded"],
  "status": "ready",
  "tags": ["sites-next"]
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/data-basic-building-blocks/data/types/Sites-Background.json
{
  "name": "Sites Background",
  "description": "This element controls the background styling for a given block",
  "id": "0a92059b-de6b-476d-b291-1638a435d0af",
  "classification": "content-type",
  "contentThumbnail": {
    "imageElement": "image",
    "source": "imageElementOrType"
  },
  "elements": [
    {
      "elementType": "group",
      "key": "backgroundColor",
      "helpText": "This element controls the background color for this item",
      "label": "Background Color",
      "typeRef": {
        "name": "Sites Color",
        "id": "93ed78a8-cea7-4188-8584-a8bedca6ebac"
      }
    },
    {
      "elementType": "toggle",
      "helpText": "This element controls if the background image is shown or not",
      "key": "includeBackgroundImage",
      "label": "Include background image"
    },
    {
      "elementType": "image",
      "helpText": "The background image",
      "key": "image",
      "label": "Image"
    },
    {
      "elementType": "optionselection",
      "helpText": "This element controls the fill behavior applied to the bakground image",
      "key": "fillOptions",
      "label": "Fill",
      "options": [
        {
          "label": "Full Width",
          "selection": "full-width"
        },
        {
          "label": "Center",
          "selection": "center"
        },
        {
          "label": "Tile",
          "selection": "tile"
        }
      ]
    },
    {
      "elementType": "text",
      "helpText": "This element is used to uniquely identify this element in the current content item",
      "key": "key",
      "label": "Key"
    }
  ],
  "kind": ["embedded"],
  "status": "ready",
  "tags": ["sites-next"],
  "rev": "0-d2cce459-3375-43a8-ad5c-b7a56addbd03"
}

=== acoustic-content-samples/prod-wch-sdk-ng9/assets/sample-email/data/types/Background-Image.json
{
  "id": "0c6b2078-02dd-4c5d-858f-99d6d88114b5",
  "rev": "3-531e65b8fe4f982c6e6a9bd7ecdc2a44",
  "name": "Background Image",
  "classification": "content-type",
  "kind": [
    "embedded"
  ],
  "contentThumbnail": {
    "imageElement": "image",
    "source": "imageElementOrType"
  },
  "description": "",
  "status": "ready",
  "tags": [],
  "elements": [
    {
      "elementType": "toggle",
      "label": "Include background image",
      "key": "includeBackgroundImage"
    },
    {
      "elementType": "image",
      "label": "Image",
      "key": "image",
      "acceptType": [
        "jpg",
        "jpeg",
        "png",
        "gif"
      ]
    },
    {
      "elementType": "optionselection",
      "options": [
        {
          "label": "Full Width",
          "selection": "full-width"
        },
        {
          "label": "Center",
          "selection": "center"
        },
        {
          "label": "Tile",
          "selection": "tile"
        }
      ],
      "label": "Fill options",
      "key": "fillOptions"
    },
    {
      "elementType": "text",
      "label": "Key",
      "key": "key"
    }
  ]
}
